version: "3"
        
services:  
    # nginx
    nginx:
        container_name: ${PROJECT_NAME}_nginx
        build: ./docker-assets/nginx
        volumes:
            - ./src:/src
            - ./docker-assets/nginx/conf.d:/etc/nginx/conf.d
        links:
            - php-fpm
        ports:
            - 8080:8080
        working_dir: /src
       
    # php
    php-fpm:
        container_name: ${PROJECT_NAME}_php-fpm
        build: ./docker-assets/php
        links:
            - mysql
            - redis
            - mailhog
        volumes:
            - ./src:/src
            - ./docker-assets/php/php.ini:/usr/local/etc/php/php.ini
        working_dir: /src/laravel
        environment:
            TZ: 'Asia/Tokyo'

        
    # database
    mysql:
        container_name: ${PROJECT_NAME}_mysql
        image: mysql:8.0.23
        volumes:
            - ./database:/var/lib/mysql
        ports:
            - 3306:3306
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: 'Asia/Tokyo'

    # adminer      
    adminer:
        container_name: ${PROJECT_NAME}_adminer
        image: adminer
        restart: always
        links:
            - mysql
        ports:
            - 6080:8080
        environment:
            ADMINER_DESIGN: 'pepa-linha'
            ADMINER_DEFAULT_SERVER: mysql

    # redis
    redis:
        container_name: ${PROJECT_NAME}_redis
        image: redis:alpine
     
    # redis commander 
    redis-commander:
        container_name: ${PROJECT_NAME}_redis_commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: always
        links:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        ports:
            - 6081:8081

    # mailhog       
    mailhog:
        container_name: ${PROJECT_NAME}_mailhog
        image: mailhog/mailhog
        ports: 
            - 1025:1025
            - 6082:8025
    
